import {
  siPython,
  siR,
  siTensorflow,
  siPytorch,
  siScikitlearn,
  siPostgresql,
  siLooker,
  siApachespark,
  siApachekafka,
  siDatabricks,
  siGooglecloud,
  siGooglebigquery,
  siQlik,
  siCloudera,
  siClaude,
  siAnthropic,
  siLangchain,
  siSpacy,
  siHuggingface,
  siYolo,
  siOpencv,
  siMlflow,
  siApacheairflow,
  siSnowflake,
  siJenkins,
  siGitlab,
  siTerraform,
  siAnsible,
  siDocker,
  siKubernetes,
  siMeta,
} from 'simple-icons';
import { LEGACY_TECH_ICONS } from './legacyTechIcons';

/** @type {Record<string, import('simple-icons').SimpleIcon>} */
export const SIMPLE_ICON_REGISTRY = {
  python: siPython,
  r: siR,
  tensorflow: siTensorflow,
  pytorch: siPytorch,
  scikitlearn: siScikitlearn,
  postgresql: siPostgresql,
  looker: siLooker,
  apachespark: siApachespark,
  apachekafka: siApachekafka,
  databricks: siDatabricks,
  googlecloud: siGooglecloud,
  googlebigquery: siGooglebigquery,
  qlik: siQlik,
  cloudera: siCloudera,
  claude: siClaude,
  anthropic: siAnthropic,
  langchain: siLangchain,
  spacy: siSpacy,
  huggingface: siHuggingface,
  yolo: siYolo,
  opencv: siOpencv,
  mlflow: siMlflow,
  apacheairflow: siApacheairflow,
  snowflake: siSnowflake,
  jenkins: siJenkins,
  gitlab: siGitlab,
  terraform: siTerraform,
  ansible: siAnsible,
  docker: siDocker,
  kubernetes: siKubernetes,
  meta: siMeta,
  ...LEGACY_TECH_ICONS,
};

export function getSimpleIcon(slug) {
  return SIMPLE_ICON_REGISTRY[slug] ?? null;
}
